mutation CreateCliAuthSession {
  createCliAuthSession {
    sessionId
    expiresAt
  }
}

query GetCliAuthSession($sessionId: String!) {
  getCliAuthSession(sessionId: $sessionId) {
    status
  }
}

mutation ConsumeCliAuthSession($sessionId: String!) {
  consumeCliAuthSession(sessionId: $sessionId) {
    token
    expireAt
  }
}

mutation Logout {
  logout {
    success
  }
}

query GetCurrentUser {
  userProfile {
    id
    email
    username
    tier
  }
}

mutation CreateLedger($name: String!, $description: String) {
  createLedger(name: $name, description: $description) {
    id
    name
    fullName
    description
    private
    createdAt
  }
}

query ListUserOwnedLedgers {
  listUserOwnedLedgers {
    id
    name
    fullName
    description
    private
    createdAt
    updatedAt
  }
}

mutation DeleteLedger($ledgerId: String!) {
  deleteLedger(ledgerId: $ledgerId) {
    ledgerId
  }
}

mutation AddEntryTransaction($ledgerId: String!, $transaction: LedgerTransactionInput!) {
  addEntryTransaction(ledgerId: $ledgerId, transaction: $transaction) {
    success
    message
  }
}

mutation AddEntryOpen($ledgerId: String!, $open: LedgerOpenInput!) {
  addEntryOpen(ledgerId: $ledgerId, open: $open) {
    success
    message
  }
}

mutation AddEntryClose($ledgerId: String!, $close: LedgerCloseInput!) {
  addEntryClose(ledgerId: $ledgerId, close: $close) {
    success
    message
  }
}

mutation AddEntryBalance($ledgerId: String!, $balance: LedgerBalanceInput!) {
  addEntryBalance(ledgerId: $ledgerId, balance: $balance) {
    success
    message
  }
}

mutation AddEntryNote($ledgerId: String!, $note: LedgerNoteInput!) {
  addEntryNote(ledgerId: $ledgerId, note: $note) {
    success
    message
  }
}

mutation AddEntryEvent($ledgerId: String!, $event: LedgerEventInput!) {
  addEntryEvent(ledgerId: $ledgerId, event: $event) {
    success
    message
  }
}

mutation AddEntryPrice($ledgerId: String!, $price: LedgerPriceInput!) {
  addEntryPrice(ledgerId: $ledgerId, price: $price) {
    success
    message
  }
}

mutation AddEntryCommodity($ledgerId: String!, $commodity: LedgerCommodityInput!) {
  addEntryCommodity(ledgerId: $ledgerId, commodity: $commodity) {
    success
    message
  }
}

mutation AddEntryBudget($ledgerId: String!, $budget: LedgerBudgetInput!) {
  addEntryBudget(ledgerId: $ledgerId, budget: $budget) {
    success
    message
  }
}

mutation AddEntryDocument($ledgerId: String!, $document: LedgerDocumentInput!) {
  addEntryDocument(ledgerId: $ledgerId, document: $document) {
    success
    message
  }
}
